server:
  port: 8081
  servlet:
    context-path: /cdc-api

cdc-engine-config:
  db.type: pgsql
  engine.name: pgsql-cdc-engine
    
  database:
      server.name: pgsql-server
      hostname: 192.168.1.201
      port: 5432
      user: demo
      password: demo
      dbname: demo_db
      
  topic.prefix: cdc-api-connector
  
  offset:
    storage: org.apache.kafka.connect.storage.FileOffsetBackingStore
    storage.file.filename: /tmp/cdc-api/offset.dat
    flush.interval.ms: 0
    flush.timeout.ms: 5000
  
  schema.history:
    internal: io.debezium.storage.file.history.FileSchemaHistory
    internal.file.filename: /tmp/cdc-api/schemahistory.dat